<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user/index", "返回"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["user/new", "新增"]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>查询结果</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Sex</th>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->id ?></td>
                <td><?php echo $user->sex ?></td>
                <td><?php echo $user->name ?></td>
                <td><?php echo $user->username ?></td>
                <td><?php echo $user->email ?></td>

                <td>
                    <?php echo $this->tag->linkTo(["user/edit/" . $user->id, "修改"]); ?>
                    <?php echo $this->tag->linkTo(["UserFiles/index/" . $user->id, "添加文档"]); ?>
                </td>
                <td><?php echo $this->tag->linkTo(["user/delete/" . $user->id, "删除"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("user/search", "第一页") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->before, "上一页") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->next, "下一页") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->last, "最后一页") ?></li>
            </ul>
        </nav>
    </div>
</div>
