<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user/search", "返回"]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>文件添加</h1>
</div>

<?php echo $this->getContent(); ?>
<?php
echo $this->tag->form(
    [
        "userFiles/saveFileByUser",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "enctype"=>"multipart/form-data"
    ]
);
?>


<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">上传用户</label>
    <div class="col-sm-10">
        <?php echo $this->tag->hiddenField(["user_id", "type" => "number", "class" => "form-control", "id" => "user_id","readonly"=>"readonly"]) ?>
        <?php echo $this->tag->textField(["user_name", "type" => "number", "class" => "form-control", "id" => "user_name","readonly"=>"readonly"]) ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">上传文件</label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(["file", "type" => "number", "class" => "form-control", "id" => "file"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["保存", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

